insert into product (id, ex_price, name, quantity, shop_id) values (1, 93152, 'Uricum acidum, Benzoicum acidum, Berber. vulg., Bryonia, Cantharis, Carduus benedictus, Ceanothus, Chelidonium majus, Chionanthus virginica, Cinchona, Dioscorea, Dolichos, Iris versicolor, Juniperus com., Nux vom.,Ptelea,Taraxacum, Carduus mar., Cynara scolymus, Solidago', 57, 12);
insert into product (id, ex_price, name, quantity, shop_id) values (2, 15652, 'Temazepam', 97, 45);
insert into product (id, ex_price, name, quantity, shop_id) values (3, 62548, 'Bumetanide', 75, 4);
insert into product (id, ex_price, name, quantity, shop_id) values (4, 61631, 'ISOPROPYL ALCOHOL', 2, 35);
insert into product (id, ex_price, name, quantity, shop_id) values (5, 18391, 'Phentermine Hydrochloride', 98, 2);
insert into product (id, ex_price, name, quantity, shop_id) values (6, 45504, 'PULSATILLA VULGARIS', 22, 34);
insert into product (id, ex_price, name, quantity, shop_id) values (7, 72715, 'Miconazole nitrate', 5, 28);
insert into product (id, ex_price, name, quantity, shop_id) values (8, 51494, 'Chlorothiazide', 33, 8);
insert into product (id, ex_price, name, quantity, shop_id) values (9, 76611, 'NAJA NAJA VENOM', 57, 27);
insert into product (id, ex_price, name, quantity, shop_id) values (10, 14880, 'Metoprolol Tartrate', 36, 6);
insert into product (id, ex_price, name, quantity, shop_id) values (11, 41552, 'Povidone Iodine', 40, 17);
insert into product (id, ex_price, name, quantity, shop_id) values (12, 97590, 'Cochlearia Officinalis, Echinacea, Hydrastis Canadensis, Lomatium Dissectum, Tabebuia Imipetiginosa, Propolis, Glandula Suprarenalis Suis', 45, 26);
insert into product (id, ex_price, name, quantity, shop_id) values (13, 80212, 'Ferrum sidereum 6', 15, 50);
insert into product (id, ex_price, name, quantity, shop_id) values (14, 67101, 'TITANIUM DIOXIDE', 34, 39);
insert into product (id, ex_price, name, quantity, shop_id) values (15, 98442, 'Menthol', 47, 49);
insert into product (id, ex_price, name, quantity, shop_id) values (16, 43039, 'English Plantain', 66, 36);
insert into product (id, ex_price, name, quantity, shop_id) values (17, 66346, 'Magnesium Hydroxide', 21, 6);
insert into product (id, ex_price, name, quantity, shop_id) values (18, 36790, 'ALCOHOL', 12, 45);
insert into product (id, ex_price, name, quantity, shop_id) values (19, 39745, 'oxycodone hydrochloride', 5, 40);
insert into product (id, ex_price, name, quantity, shop_id) values (20, 56061, 'Mandragora Arnica', 95, 35);
insert into product (id, ex_price, name, quantity, shop_id) values (21, 22246, 'Povidone-iodine', 6, 13);
insert into product (id, ex_price, name, quantity, shop_id) values (22, 82224, 'Levalbuterol', 4, 9);
insert into product (id, ex_price, name, quantity, shop_id) values (23, 42113, 'TRICLOSAN', 15, 6);
insert into product (id, ex_price, name, quantity, shop_id) values (24, 39033, 'acetaminophen', 2, 42);
insert into product (id, ex_price, name, quantity, shop_id) values (25, 17842, 'MUCOR PLUMBEUS', 36, 17);
insert into product (id, ex_price, name, quantity, shop_id) values (26, 17414, 'Zolpidem Tartrate', 4, 39);
insert into product (id, ex_price, name, quantity, shop_id) values (27, 99130, 'Childrens Mucinex Cough', 6, 15);
insert into product (id, ex_price, name, quantity, shop_id) values (28, 46454, 'Ibuprofen', 44, 50);
insert into product (id, ex_price, name, quantity, shop_id) values (29, 16534, 'Ibuprofen', 70, 41);
insert into product (id, ex_price, name, quantity, shop_id) values (30, 56976, 'Hydrogen Peroxide', 88, 7);
insert into product (id, ex_price, name, quantity, shop_id) values (31, 96843, 'Gabapentin', 95, 42);
insert into product (id, ex_price, name, quantity, shop_id) values (32, 17342, 'Miconazole nitrate', 12, 45);
insert into product (id, ex_price, name, quantity, shop_id) values (33, 96827, 'Morphine Sulfate', 76, 42);
insert into product (id, ex_price, name, quantity, shop_id) values (34, 57611, 'SODIUM FLUORIDE', 87, 4);
insert into product (id, ex_price, name, quantity, shop_id) values (35, 16459, 'Fluorescein Sodium and Benoxinate Hydrochloride', 31, 1);
insert into product (id, ex_price, name, quantity, shop_id) values (36, 81330, 'Methocarbamol', 86, 48);
insert into product (id, ex_price, name, quantity, shop_id) values (37, 50573, 'Pullularia pullulans', 3, 24);
insert into product (id, ex_price, name, quantity, shop_id) values (38, 20685, 'OCTINOXATE', 86, 15);
insert into product (id, ex_price, name, quantity, shop_id) values (39, 69687, 'SHEA BUTTER', 41, 6);
insert into product (id, ex_price, name, quantity, shop_id) values (40, 19683, 'Lisinopril', 53, 3);
insert into product (id, ex_price, name, quantity, shop_id) values (41, 34476, 'Quercus gambelii', 56, 47);
insert into product (id, ex_price, name, quantity, shop_id) values (42, 90987, 'Simvastatin', 49, 21);
insert into product (id, ex_price, name, quantity, shop_id) values (43, 63466, 'simvastatin', 28, 5);
insert into product (id, ex_price, name, quantity, shop_id) values (44, 25751, 'LEVOTHYROXINE, LIOTHYRONINE', 51, 43);
insert into product (id, ex_price, name, quantity, shop_id) values (45, 87635, 'Aluminum Zirconium Octachlorohydrex Gly', 79, 27);
insert into product (id, ex_price, name, quantity, shop_id) values (46, 83213, 'UREA', 86, 9);
insert into product (id, ex_price, name, quantity, shop_id) values (47, 97331, 'Alcohol', 37, 40);
insert into product (id, ex_price, name, quantity, shop_id) values (48, 81170, 'Bupropion Hydrochloride', 27, 40);
insert into product (id, ex_price, name, quantity, shop_id) values (49, 25510, 'Chili pepper, Green pepper, Potato, Tobacco, Tomato, Eggplant, Nux vomica, Pulsatilla,', 81, 2);
insert into product (id, ex_price, name, quantity, shop_id) values (50, 91986, 'ATAZANAVIR SULFATE', 62, 33);
